In [1]:
import numpy as np

###  2.Print the numpy version and the configuration

In [2]:
print(np.__version__)
np.show_config()

1.14.3
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rajusunkara/Documents/anakonda/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rajusunkara/Documents/anakonda/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rajusunkara/Documents/anakonda/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rajusunkara/Documents/anakonda/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rajusunkara/Documents/anakonda/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rajusunkara/Documents/anakonda/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rajusunkara/Documents/anakonda/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAV

###  3.Create a null vector of size 10

In [5]:
Z = np.zeros(11)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


###  4.Find the memory size of any array 

In [19]:
Z = np.zeros((11,11))

print(Z.size,"Bytes")
print("%d bytes" % (Z.size * Z.itemsize))

121 Bytes
968 bytes


In [1]:
# 5. get the documentation of the numpy add function from the command line

%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


In [9]:
# 6. Create a null vector of size 10 but the fifth value which is 10
import numpy as np

Z = np.zeros(10, dtype=int)
Z[4] = 10
print(np.reshape(Z,(2,5)))

[[ 0  0  0  0 10]
 [ 0  0  0  0  0]]


In [10]:
# 7. Create a vector with values ranging from 10 to 49

n = np.arange(10,49)
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [11]:
# 8. Reverse a vector (first element becomes last)

n = np.arange(10,40)
n = n[::-1]
print(n)

[39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16
 15 14 13 12 11 10]


In [17]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8

v = np.arange(0,9, dtype=float)
print(np.reshape(v,(3,3)))


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [22]:
# 10. Create a 3x3 identity matrix 

d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
# 12. Create a 3x3x3 array with random values

d2 = np.random.random((3,3,3))
print(d2)

[[[0.24111494 0.07305606 0.33909498]
  [0.20245842 0.65173729 0.45124558]
  [0.78943526 0.07192443 0.51495602]]

 [[0.80965662 0.397957   0.13713107]
  [0.04823421 0.76123947 0.99204272]
  [0.01588375 0.98537165 0.33840316]]

 [[0.57105037 0.65251084 0.86822601]
  [0.09041321 0.60766157 0.93968833]
  [0.63568371 0.7515805  0.5597408 ]]]


In [24]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values 

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.03216353479899148 0.9939108694904285


In [25]:
# 14. Create a random vector of size 30 and find the mean value 

Z = np.random.random(30)
m = Z.mean()
print(m)

0.5395771412512943


In [31]:
# 15. Create a 2d array with 1 on the border and 0 inside

Z = np.ones((10,10), dtype=int)
Z[1:-1,1:-1] = 0
print(Z)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [39]:
# 16. How to add a border (filled with 0's) around an existing array? 

z1 = np.zeros((10,10), dtype = int)
z1 = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(z1)

[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]


In [2]:
# 17. Result of the following expression.
import numpy as np

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [5]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [6]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [7]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [8]:
# 21. Create a checkerboard 8x8 matrix using the tile function

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [18]:
# 22. Normalize a 5x5 range matrix
v = np.arange(0,25, dtype=int)


Z = np.reshape(v,(5,5))
Z1 = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(np.float_(Z))

[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


In [3]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) 
import numpy as np 

color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [15]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)



[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [16]:
# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [21]:
# 25.Given a 1D array, negate (add negative sign) all elements which are between 3 and 8, in place.

arr1 = np.arange(11)
arr1[(3 < arr1) & (arr1 <= 8)] *= -1

print(arr1)


[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [22]:
# 26. The output of the following script

# Author: Sandeep Parimi

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [27]:
# 27. Consider an integer vector Z, which of these expressions are legal? 

arr1 = Z
Z**Z




array([[27., 27.],
       [27., 27.],
       [27., 27.],
       [27., 27.],
       [27., 27.]])

In [28]:

Z <- Z


array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [29]:
2 << Z >> 2


TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [30]:

1j*Z


array([[0.+3.j, 0.+3.j],
       [0.+3.j, 0.+3.j],
       [0.+3.j, 0.+3.j],
       [0.+3.j, 0.+3.j],
       [0.+3.j, 0.+3.j]])

In [31]:

Z/1/1


array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [32]:

Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [1]:
import numpy as np

In [2]:
#28 The result of the following expressions

print(np.array(0) / np.array(0))

nan


/Users/rajusunkara/Documents/anakonda/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [3]:

print(np.array(0) // np.array(0))

0


/Users/rajusunkara/Documents/anakonda/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [4]:

print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


In [5]:
# 29 Round away from zero a float array.


Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 6.  9.  8. -4.  4. -2. -6.  9.  3. 10.]


In [8]:
# 30 Find common values between two arrays

Z1 = np.random.randint(0,10,10)
print(Z1)

[6 7 8 6 7 5 8 2 9 4]


In [9]:

Z2 = np.random.randint(0,10,10)
print(Z2)

[9 6 3 8 8 5 0 2 5 5]


In [10]:

print(np.intersect1d(Z1,Z2))

[2 5 6 8 9]


In [12]:
# 31 Ignore all numpy warnings (not recommended)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

print(Z)

[inf]


In [13]:
# Back to sanity
_ = np.seterr(**defaults)
print(_)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}


In [16]:
# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0
    print(Z)

[inf]


In [17]:
# 32 Is the following expressions true?

np.sqrt(-1) == np.emath.sqrt(-1)

False

In [18]:
print(np.sqrt(-1))

nan


In [19]:
print(np.emath.sqrt(-1))

1j


In [21]:
# 33 Get the dates of yesterday, today and tomorrow.

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday,today,tomorrow)

2018-09-21 2018-09-22 2018-09-23


In [22]:
# 34 To get all the dates corresponding to the month of July 2016.

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [27]:
# 35 To compute ((A+B)*(-A/2)) in place (without copy).
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3


In [28]:
print(A)

[1. 1. 1.]


In [29]:
print(B)

[2. 2. 2.]


In [30]:
print(C)

[3. 3. 3.]


In [31]:
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [32]:
# 36 Extract the integer part of a random array using 5 different methods

Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[1. 1. 3. 6. 1. 6. 3. 0. 5. 1.]
[1. 1. 3. 6. 1. 6. 3. 0. 5. 1.]
[1. 1. 3. 6. 1. 6. 3. 0. 5. 1.]
[1 1 3 6 1 6 3 0 5 1]
[1. 1. 3. 6. 1. 6. 3. 0. 5. 1.]


In [33]:
# 37 Create a 5x5 matrix with row values ranging from 0 to 4

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [34]:
# Typecast the matrix  
Z.astype(int)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [36]:
# Transpose the matrix

Z.astype(int).transpose()

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [37]:
# 38 Consider a generator function that generates 10 integers and use it to build an array.

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [43]:
Z = np.arange(0,10)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
Z = np.arange(0,10,dtype=float)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [46]:
# 39 Create a vector of size 10 with values ranging from 0 to 1, both excluded

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [51]:
# 40 Create a random vector of size 10 and sort it 

Z = np.random.random(10)
Z.sort()
print(Z)

[0.11661107 0.25689048 0.41783103 0.42135093 0.51978379 0.54051918
 0.60906216 0.66849982 0.94162634 0.96182446]


In [54]:
# 41 How to sum a small array faster than np.sum?

Z = np.arange(10)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [55]:
np.add.reduce(Z)

45

In [58]:
# 42 Consider two random array A and B, check if they are equal

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)


In [60]:
print(A)
print(B)

[1 0 0 1 0]
[1 1 0 0 1]


In [61]:
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [62]:

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False


In [69]:
# 43 Make an array immutable (read-only)

Z = np.zeros(10)
print(Z)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [66]:

print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [70]:
Z[1]=1
print(Z)

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


In [71]:

Z.flags.writeable = False
# Try to assign the value at 0th position
Z[0] = 1

ValueError: assignment destination is read-only

In [74]:
# 44 Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

Z = np.random.random((10,2))

print(Z)

[[0.62972267 0.70890843]
 [0.22337475 0.62393755]
 [0.78835776 0.07577992]
 [0.70636022 0.30880643]
 [0.97295244 0.48244873]
 [0.51954672 0.78164994]
 [0.45024462 0.08008634]
 [0.01795005 0.67927216]
 [0.23862107 0.7818358 ]
 [0.50415429 0.63162494]]


In [75]:

X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)

print(R)
print(T)

[0.94820978 0.66271739 0.79199151 0.77091256 1.08599873 0.93856562
 0.45731175 0.67950928 0.81743944 0.8081594 ]
[0.84448359 1.22700516 0.09582934 0.41214166 0.46033057 0.98417068
 0.17603188 1.54437706 1.27457014 0.89716237]


In [80]:
# 45 Create random vector of size 10 and replace the maximum value by 0 

Z = np.random.random(10)
print(Z)

[0.01717486 0.35003439 0.86603317 0.88405284 0.34765433 0.2956643
 0.85681977 0.44505641 0.87448395 0.42606469]


In [81]:
Z[Z.argmax()] = 0
print(Z)

[0.01717486 0.35003439 0.86603317 0.         0.34765433 0.2956643
 0.85681977 0.44505641 0.87448395 0.42606469]


In [82]:
# 46 Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

Z = np.zeros((5,5), [('x',float),('y',float)])
print(Z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]


In [83]:

Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [84]:
# 47 Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [86]:
# 48. Print the minimum and maximum representable value for each numpy scalar type

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [87]:
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [91]:
# 49. How to print all the values of an array?

np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [92]:
# 50. How to find the closest value (to a given scalar) in a vector?

Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

88


In [93]:
# 51. Create a structured array representing a position (x,y) and a color (r,g,b)

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [95]:
# 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)


[[0.         0.06147708 0.27521846 0.62458581 0.39092644 0.28520454
  0.38716909 0.46170721 0.34657266 0.38105479]
 [0.06147708 0.         0.21683903 0.65552338 0.33305152 0.24667565
  0.4478458  0.51933349 0.29000453 0.41948644]
 [0.27521846 0.21683903 0.         0.83931057 0.11626754 0.1456426
  0.66145214 0.69977386 0.07595838 0.62021155]
 [0.62458581 0.65552338 0.83931057 0.         0.9454285  0.90217815
  0.49376189 0.73599946 0.91425395 0.25146037]
 [0.39092644 0.33305152 0.11626754 0.9454285  0.         0.19339768
  0.77611886 0.80206538 0.04796559 0.7327329 ]
 [0.28520454 0.24667565 0.1456426  0.90217815 0.19339768 0.
  0.63981905 0.62745892 0.15039182 0.66440894]
 [0.38716909 0.4478458  0.66145214 0.49376189 0.77611886 0.63981905
  0.         0.24225597 0.73036642 0.2932363 ]
 [0.46170721 0.51933349 0.69977386 0.73599946 0.80206538 0.62745892
  0.24225597 0.         0.75410284 0.52562094]
 [0.34657266 0.29000453 0.07595838 0.91425395 0.04796559 0.15039182
  0.73036642 0.754102

In [97]:
# Much faster with scipy
import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.51299972 0.37591972 0.33686216 0.388716   0.26634067
  0.20868833 0.39936924 0.28307056 0.60897177]
 [0.51299972 0.         0.82002091 0.78546872 0.14365701 0.26351748
  0.51454398 0.24744089 0.77550046 0.89215245]
 [0.37591972 0.82002091 0.         0.51320129 0.67749695 0.6187414
  0.56293492 0.61892833 0.40029439 0.33415768]
 [0.33686216 0.78546872 0.51320129 0.         0.68889037 0.52264122
  0.27766595 0.72738932 0.11364482 0.83377875]
 [0.388716   0.14365701 0.67749695 0.68889037 0.         0.17997637
  0.43457135 0.12948519 0.66368906 0.75465731]
 [0.26634067 0.26351748 0.6187414  0.52264122 0.17997637 0.
  0.25739717 0.27135312 0.51346146 0.77536458]
 [0.20868833 0.51454398 0.56293492 0.27766595 0.43457135 0.25739717
  0.         0.50122954 0.30189029 0.81733302]
 [0.39936924 0.24744089 0.61892833 0.72738932 0.12948519 0.27135312
  0.50122954 0.         0.68242307 0.64824492]
 [0.28307056 0.77550046 0.40029439 0.11364482 0.66368906 0.51346146
  0.30189029 0.682423

In [99]:
# 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

Z = np.arange(10, dtype=np.float32)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [101]:
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [102]:
# 54. How to read the following file?

from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [103]:
# 55. What is the equivalent of enumerate for numpy arrays?

Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [104]:

for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [105]:
# 56. Generate a generic 2D Gaussian-like array

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [106]:
# 57. How to randomly place p elements in a 2D array? 

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [108]:
# 58. Subtract the mean of each row of a matrix

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

print(Y)

[[ 0.13113962  0.43533424  0.35608829 -0.16538355 -0.33902623  0.2674824
  -0.17979451 -0.24389769  0.2336421  -0.49558467]
 [-0.01216092 -0.20746977 -0.21134592 -0.24124598  0.44117301  0.42763543
  -0.24048821 -0.25771383  0.49676489 -0.1951487 ]
 [ 0.15608937  0.38760463 -0.03575742  0.37478014 -0.34574488 -0.42263835
   0.15271676 -0.04295648  0.20632315 -0.43041692]
 [ 0.37038525 -0.35123224  0.52870444 -0.12378118  0.39226736 -0.27920095
   0.16161831 -0.41587378  0.12443001 -0.40731723]
 [-0.12176488  0.21060784  0.27045066 -0.44490468  0.35378245 -0.23760318
  -0.31580513  0.12991446 -0.2595507   0.41487317]]


In [109]:

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.13113962  0.43533424  0.35608829 -0.16538355 -0.33902623  0.2674824
  -0.17979451 -0.24389769  0.2336421  -0.49558467]
 [-0.01216092 -0.20746977 -0.21134592 -0.24124598  0.44117301  0.42763543
  -0.24048821 -0.25771383  0.49676489 -0.1951487 ]
 [ 0.15608937  0.38760463 -0.03575742  0.37478014 -0.34574488 -0.42263835
   0.15271676 -0.04295648  0.20632315 -0.43041692]
 [ 0.37038525 -0.35123224  0.52870444 -0.12378118  0.39226736 -0.27920095
   0.16161831 -0.41587378  0.12443001 -0.40731723]
 [-0.12176488  0.21060784  0.27045066 -0.44490468  0.35378245 -0.23760318
  -0.31580513  0.12991446 -0.2595507   0.41487317]]


In [111]:
# 59. How to sort an array by the nth(2 nd) column? 

Z = np.random.randint(0,10,(3,3))
print(Z)

[[6 7 2]
 [1 9 7]
 [9 8 0]]


In [112]:

print(Z[Z[:,1].argsort()])

[[6 7 2]
 [9 8 0]
 [1 9 7]]


In [118]:
# 60. How to tell if a given 2D array has null columns?

Z = np.random.randint(0,3,(3,10))
print(Z)

[[1 2 0 0 2 1 2 2 0 1]
 [1 1 2 0 1 2 0 0 2 1]
 [1 1 1 0 2 1 0 2 0 0]]


In [119]:
print((~Z.any(axis=0)).any())

True


In [120]:
# 61. Find the nearest value from a given value in an array

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.6179137778157616


In [139]:
# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
print(A)
print(B)

[[0]
 [1]
 [2]]
[[0 1 2]]


In [140]:
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [141]:
# 63. Create an array class that has a name attribute 

class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [142]:
# 64. Consider a given vector, 
#     how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)



[4. 3. 3. 1. 3. 5. 1. 6. 2. 2.]


In [143]:
# Another solution
np.add.at(Z, I, 1)
print(Z)

[ 7.  5.  5.  1.  5.  9.  1. 11.  3.  3.]


In [144]:
print(Z.astype(int))

[ 7  5  5  1  5  9  1 11  3  3]


In [145]:
# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? 

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [146]:
# 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


In [148]:
# 67. Considering a four dimensions array, how to get sum over the last two axis at once?

A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)


[[40 53 60 78]
 [47 49 61 57]
 [52 71 55 36]]


In [149]:
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[40 53 60 78]
 [47 49 61 57]
 [52 71 55 36]]


In [151]:
# 68. Considering a one-dimensional vector D, 
# how to compute means of subsets of D using a vector S of same size describing subset indices?

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)



[0.39227622 0.47442978 0.53750369 0.38469148 0.52441307 0.50692405
 0.54947319 0.43513082 0.46343927 0.62980504]


In [152]:
# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.392276
1    0.474430
2    0.537504
3    0.384691
4    0.524413
5    0.506924
6    0.549473
7    0.435131
8    0.463439
9    0.629805
dtype: float64


In [153]:
# 69. How to get the diagonal of a dot product?


A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

print(A)
print(B)

[[0.13904737 0.35659179 0.01947817 0.91501307 0.51742959]
 [0.83363326 0.16428507 0.22982939 0.31135735 0.33856038]
 [0.18167057 0.52410496 0.61757797 0.86765161 0.4900835 ]
 [0.321727   0.20503681 0.07135733 0.05993363 0.29865917]
 [0.56773703 0.64612881 0.18137733 0.64718424 0.14644536]]
[[0.70900462 0.77355092 0.79115496 0.91226183 0.33980894]
 [0.72803211 0.94551029 0.36079579 0.27231722 0.14437801]
 [0.34645361 0.24349733 0.7178797  0.79705847 0.39470572]
 [0.73606788 0.59836223 0.6558758  0.66958222 0.73616363]
 [0.08907174 0.21107394 0.47417446 0.98100876 0.25222537]]


In [154]:
# Slow version  
np.diag(np.dot(A, B))


array([1.08454386, 1.1139196 , 1.5776279 , 0.73932804, 0.87117031])

In [155]:

# Fast version
np.sum(A * B.T, axis=1)


array([1.08454386, 1.1139196 , 1.5776279 , 0.73932804, 0.87117031])

In [157]:

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.08454386, 1.1139196 , 1.5776279 , 0.73932804, 0.87117031])

In [158]:
# 70. Consider the vector [1, 2, 3, 4, 5], 
# how to build a new vector with 3 consecutive zeros interleaved between each value? 

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [160]:
# 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A)
print(B)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [161]:
# Applied multiplication operation

print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [163]:
# 72. How to swap two rows of an array? 

A = np.arange(25).reshape(5,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [164]:
# Let's swap first and second rows

A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [166]:
print(F)

[[53 99]
 [78 99]
 [53 78]
 [60 66]
 [60 79]
 [66 79]
 [62 86]
 [86 94]
 [62 94]
 [16 60]
 [16 39]
 [39 60]
 [18 73]
 [39 73]
 [18 39]
 [36 96]
 [34 96]
 [34 36]
 [ 7 14]
 [ 7 30]
 [14 30]
 [ 9  9]
 [ 9 50]
 [ 9 50]
 [24 50]
 [16 24]
 [16 50]
 [81 91]
 [17 81]
 [17 91]]


In [165]:
# 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), 
# find the set of unique line segments composing all the triangles 


faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 7, 14) ( 7, 30) ( 9,  9) ( 9, 50) (14, 30) (16, 24) (16, 39) (16, 50)
 (16, 60) (17, 81) (17, 91) (18, 39) (18, 73) (24, 50) (34, 36) (34, 96)
 (36, 96) (39, 60) (39, 73) (53, 78) (53, 99) (60, 66) (60, 79) (62, 86)
 (62, 94) (66, 79) (78, 99) (81, 91) (86, 94)]


In [169]:
# 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?

C = np.bincount([1,1,2,3,4,4,6])
print(C)

[0 2 1 1 2 0 1]


In [170]:
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [172]:
# 75. How to compute averages using a sliding window over an array? 

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [173]:
# 76. Consider a one-dimensional array Z, build a two-dimensional array whose 
#     first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [175]:
# 77. How to negate a boolean, or to change the sign of a float inplace? 

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
print(Z)

[1 1 1 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 1 0
 1 0 1 1 0 1 0 1 1 1 1 1 1 0 0 0 0 1 0 0 1 1 0 1 1 0 0 1 0 1 1 0 0 1 0 1 1
 1 1 1 0 1 0 0 0 1 1 0 1 1 0 0 1 1 1 0 0 0 1 1 1 0 0]


In [176]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)
print(Z)

[-0.78170779  0.99805691  0.59687468  0.82683254  0.48925287  0.94749225
 -0.4961958   0.77433881 -0.11626822  0.21801718 -0.44884558  0.74243451
 -0.91904731  0.75926893  0.99479688 -0.06591639  0.93406734 -0.56949722
  0.4069853   0.43884633  0.69398779 -0.44693657  0.68229446  0.92140352
 -0.18910889 -0.45269661 -0.96200623  0.57944388  0.60451805 -0.40376643
 -0.81167906  0.01153996  0.5919669  -0.68350209 -0.44456724 -0.35486913
  0.78698011  0.98631372  0.97623786  0.57100931 -0.11199486 -0.9817374
  0.9919786   0.56666608 -0.83794461  0.00111384 -0.60048196 -0.4473865
 -0.04234478  0.33617572 -0.36828039 -0.55232938 -0.00572004  0.21794547
 -0.18218264 -0.42840535 -0.76720045  0.01241986 -0.61174478  0.62657099
 -0.57662874 -0.95157725 -0.85365372 -0.61081891 -0.33442654  0.94865271
 -0.16430947  0.80033123 -0.2531526   0.51371884  0.53353817 -0.24292365
  0.56971737  0.59148019 -0.21769964 -0.39223567 -0.47490749 -0.50169833
 -0.52836634  0.10571532 -0.12144934 -0.3801583  -0.5

In [178]:
# 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, 
#     how to compute distance from p to each line i (P0[i],P1[i])?

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print(distance(P0, P1, p))

[6.69732468 1.93904308 6.099537   5.60881454 2.03432692 5.71654868
 0.93237049 6.22278073 1.79550365 0.60904983]


In [180]:
# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, 
#     how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))

print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[8.01165901e+00 2.67113398e+00 5.84315503e+00 9.32002271e+00
  2.51100221e+00 9.23735934e+00 9.58287182e+00 3.80123332e+00
  8.84303931e+00 7.98292824e+00]
 [1.47175027e+01 2.11234818e+00 9.37305778e+00 1.59739809e+01
  4.01579708e+00 1.57473717e+01 1.58323617e+01 1.72009842e+00
  1.45168966e+01 1.41897217e+01]
 [1.25805672e+01 8.54247098e+00 3.38262734e+00 1.35967165e+01
  4.81102374e+00 1.28755941e+01 1.73855525e+01 4.01683773e+00
  1.71527511e+01 1.58400344e+01]
 [1.48856971e+01 2.35809290e+00 9.25943975e+00 1.61302017e+01
  4.29895544e+00 1.58775303e+01 1.61363850e+01 1.40198782e+00
  1.48438431e+01 1.44961439e+01]
 [1.38948470e+01 1.55791193e+00 1.18496891e+01 1.53112977e+01
  1.49575498e+00 1.54255042e+01 1.29459130e+01 5.80276547e+00
  1.11633149e+01 1.12585672e+01]
 [6.57227935e-01 4.10410281e-01 4.20814035e+00 2.14055433e+00
  1.09905214e+01 2.46412923e+00 1.09972583e+00 9.02526603e+00
  5.77899808e-01 4.91777089e-01]
 [1.01771675e+00 9.87273334e-01 5.46224689e+00 2.55444300e

In [181]:
# 80. Consider an arbitrary array, write a function that extract a subpart with 
#    a fixed shape and centered on a given element (pad with a fill value when necessary)

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[7 5 7 8 4 3 3 2 8 3]
 [3 5 9 7 0 0 3 1 1 4]
 [8 7 8 4 4 1 6 1 6 7]
 [4 5 5 1 8 9 7 5 5 7]
 [1 7 2 8 4 6 7 8 0 2]
 [6 6 7 2 6 2 2 9 1 6]
 [8 1 5 8 4 0 1 9 2 7]
 [7 6 4 7 2 5 8 8 3 9]
 [0 6 7 7 7 9 6 4 9 9]
 [1 0 5 9 9 8 9 0 5 8]]
[[0 0 0 0 0]
 [0 7 5 7 8]
 [0 3 5 9 7]
 [0 8 7 8 4]
 [0 4 5 5 1]]


In [182]:
# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array 
#    R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [183]:
# 82. Compute a matrix rank

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [184]:
# 83. How to find the most frequent value in an array?

Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


In [186]:
# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

Z = np.random.randint(0,5,(10,10))
print(Z)

[[4 4 4 1 1 1 3 1 2 3]
 [0 0 3 1 4 3 0 2 3 3]
 [1 3 4 4 3 3 4 1 0 2]
 [3 2 1 4 3 4 3 3 0 2]
 [1 0 1 2 1 0 0 4 3 4]
 [4 3 2 1 0 0 1 0 0 3]
 [2 1 4 0 1 3 2 2 4 4]
 [3 1 0 0 1 3 1 0 4 0]
 [0 3 0 4 0 3 3 2 1 2]
 [4 4 2 2 2 1 1 1 4 3]]


In [187]:
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 4 4]
   [0 0 3]
   [1 3 4]]

  [[4 4 1]
   [0 3 1]
   [3 4 4]]

  [[4 1 1]
   [3 1 4]
   [4 4 3]]

  [[1 1 1]
   [1 4 3]
   [4 3 3]]

  [[1 1 3]
   [4 3 0]
   [3 3 4]]

  [[1 3 1]
   [3 0 2]
   [3 4 1]]

  [[3 1 2]
   [0 2 3]
   [4 1 0]]

  [[1 2 3]
   [2 3 3]
   [1 0 2]]]


 [[[0 0 3]
   [1 3 4]
   [3 2 1]]

  [[0 3 1]
   [3 4 4]
   [2 1 4]]

  [[3 1 4]
   [4 4 3]
   [1 4 3]]

  [[1 4 3]
   [4 3 3]
   [4 3 4]]

  [[4 3 0]
   [3 3 4]
   [3 4 3]]

  [[3 0 2]
   [3 4 1]
   [4 3 3]]

  [[0 2 3]
   [4 1 0]
   [3 3 0]]

  [[2 3 3]
   [1 0 2]
   [3 0 2]]]


 [[[1 3 4]
   [3 2 1]
   [1 0 1]]

  [[3 4 4]
   [2 1 4]
   [0 1 2]]

  [[4 4 3]
   [1 4 3]
   [1 2 1]]

  [[4 3 3]
   [4 3 4]
   [2 1 0]]

  [[3 3 4]
   [3 4 3]
   [1 0 0]]

  [[3 4 1]
   [4 3 3]
   [0 0 4]]

  [[4 1 0]
   [3 3 0]
   [0 4 3]]

  [[1 0 2]
   [3 0 2]
   [4 3 4]]]


 [[[3 2 1]
   [1 0 1]
   [4 3 2]]

  [[2 1 4]
   [0 1 2]
   [3 2 1]]

  [[1 4 3]
   [1 2 1]
   [2 1 0]]

  [[4 3 4]
   [2 1 0]
   [1 0 0]]

  [[3 4 3]
   

In [188]:
# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9 14 11  5  7]
 [14  0 12 17  0]
 [11 12  9 42  9]
 [ 5 17 42  3 16]
 [ 7  0  9 16  9]]


In [192]:
# 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). 
#    How to compute the sum of of the p matrix products at once? (result has shape (n,1)).

p, n = 10, 20
M = np.ones((p,n,n))
print(M)

# It works, because:
# M is (p,n,n)

[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1

In [193]:
V = np.ones((p,n,1))
print(V)

# V is (p,n,1)

[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]

In [194]:
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [196]:
# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

Z = np.ones((16,16))
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [197]:
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [198]:
# 88. How to implement the Game of Life using numpy arrays?

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [199]:
# 89. How to get the n largest values of an array

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [201]:

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9997 9998 9999 9996 9995]


In [202]:
# 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 


def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [204]:
# 91. How to create a record array from a regular array? 

Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
print(Z)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]


In [205]:
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [213]:
# 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods 

x = np.random.rand(5e7)

TypeError: 'float' object cannot be interpreted as an integer

In [212]:

x = np.random.rand(537)


In [209]:
%timeit np.power(x,3)

29.4 µs ± 1.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [210]:

%timeit x*x*x

3.78 µs ± 238 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [211]:

%timeit np.einsum('i,i,i->i',x,x,x)

7.03 µs ± 153 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [214]:
# 93. Consider two arrays A and B of shape (8,3) and (2,2). 
#   How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? 

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

print(A)
print(B)

[[3 4 2]
 [3 2 4]
 [0 4 2]
 [2 3 2]
 [3 0 4]
 [3 2 0]
 [0 0 1]
 [4 2 3]]
[[3 3]
 [4 3]]


In [215]:
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 3 4 5 7]


In [216]:
# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) 

Z = np.random.randint(0,5,(10,3))
print(Z)

[[4 2 1]
 [0 1 0]
 [0 1 1]
 [1 4 0]
 [4 0 3]
 [4 4 4]
 [0 1 1]
 [2 1 2]
 [4 2 4]
 [2 1 4]]


In [217]:

# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[4 2 1]
 [0 1 0]
 [0 1 1]
 [1 4 0]
 [4 0 3]
 [0 1 1]
 [2 1 2]
 [4 2 4]
 [2 1 4]]


In [218]:

# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 2 1]
 [0 1 0]
 [0 1 1]
 [1 4 0]
 [4 0 3]
 [0 1 1]
 [2 1 2]
 [4 2 4]
 [2 1 4]]


In [219]:
# 95. Convert a vector of ints into a matrix binary representation

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [220]:

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [222]:
# 96. Given a two dimensional array, how to extract unique rows? 

Z = np.random.randint(0,2,(6,3))
print(Z)

[[0 0 0]
 [1 1 0]
 [0 1 1]
 [1 0 0]
 [0 0 1]
 [1 0 0]]


In [223]:
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [1 1 0]]


In [225]:
# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

print(A)
print(B)


[0.92205497 0.53486799 0.91789119 0.5937309  0.17903145 0.58374546
 0.42217569 0.62015495 0.55472091 0.48854274]
[0.12315148 0.48262809 0.23441974 0.53404957 0.53705288 0.21378175
 0.86701009 0.73215482 0.82598775 0.55391416]


In [226]:

np.einsum('i->', A)       # np.sum(A)


5.816916245996676

In [227]:

np.einsum('i,i->i', A, B) # A * B


array([0.11355243, 0.25814232, 0.21517182, 0.31708173, 0.09614936,
       0.12479413, 0.36603059, 0.45404944, 0.45819267, 0.27061074])

In [229]:

np.einsum('i,i', A, B)    # np.inner(A, B)


2.673775213439307

In [230]:

np.einsum('i,j->ij', A, B)    # np.outer(A, B)


array([[0.11355243, 0.44500963, 0.21614789, 0.49242306, 0.49519228,
        0.19711852, 0.79943096, 0.67508699, 0.76160611, 0.5107393 ],
       [0.06586978, 0.25814232, 0.12538362, 0.28564602, 0.2872524 ,
        0.11434502, 0.46373595, 0.39160618, 0.44179441, 0.29627095],
       [0.11303965, 0.44300007, 0.21517182, 0.49019939, 0.49295611,
        0.19622838, 0.79582092, 0.67203846, 0.75816688, 0.50843292],
       [0.07311884, 0.28655121, 0.13918225, 0.31708173, 0.31886489,
        0.12692883, 0.51477069, 0.43470294, 0.49041445, 0.32887595],
       [0.02204799, 0.08640561, 0.04196851, 0.09561167, 0.09614936,
        0.03827366, 0.15522207, 0.13107874, 0.14787778, 0.09916805],
       [0.07188911, 0.28173196, 0.13684146, 0.31174901, 0.31350218,
        0.12479413, 0.50611321, 0.42739205, 0.4821666 , 0.32334487],
       [0.05199156, 0.20375385, 0.09896632, 0.22546275, 0.22673067,
        0.09025346, 0.36603059, 0.30909797, 0.34871195, 0.23384909],
       [0.076373  , 0.2993042 , 0.1453765

In [233]:
# 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

print(x)
print(y)

[  0.           0.09950042   0.19601332   0.28660095   0.3684244
   0.43879128   0.49520137   0.53538953   0.55736537   0.55944897
   0.54030231   0.49895573   0.43482931   0.34774848   0.237954
   0.1061058   -0.04671924  -0.21903564  -0.40896377  -0.61425018
  -0.83229367  -1.06017682  -1.29470246  -1.53243485  -1.76974492
  -2.00285904  -2.22791076  -2.44099478  -2.63822255  -2.81577868
  -2.96997749  -3.09731897  -3.19454328  -3.25868324  -3.28711385
  -3.27759841  -3.2283303   -3.13797012  -3.00567731  -2.83113599
  -2.61457448  -2.35677818  -2.05909545  -1.72343644  -1.35226463
  -0.9485811   -0.51590162  -0.05822672   0.41999512   0.91391061
   1.41831093   1.92768649   2.43628669   2.93818398   3.42734153
   3.89768376   4.34316892   4.75786287   5.1360132    5.47212274
   5.76102172   5.99793747   6.178561     6.29910941   6.35638348
   6.34781957   6.27153511   6.12636709   5.91190293   5.62850319
   5.27731578   4.86028133   4.38012946   3.84036588   3.24525022
   2.59976488

In [235]:


dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
print(r_int)

[  0.           2.48788858   4.97577716   7.46366574   9.95155432
  12.43944289  14.92733147  17.41522005  19.90310863  22.39099721
  24.87888579  27.36677437  29.85466295  32.34255152  34.8304401
  37.31832868  39.80621726  42.29410584  44.78199442  47.269883
  49.75777158  52.24566016  54.73354873  57.22143731  59.70932589
  62.19721447  64.68510305  67.17299163  69.66088021  72.14876879
  74.63665736  77.12454594  79.61243452  82.1003231   84.58821168
  87.07610026  89.56398884  92.05187742  94.539766    97.02765457
  99.51554315 102.00343173 104.49132031 106.97920889 109.46709747
 111.95498605 114.44287463 116.9307632  119.41865178 121.90654036
 124.39442894 126.88231752 129.3702061  131.85809468 134.34598326
 136.83387184 139.32176041 141.80964899 144.29753757 146.78542615
 149.27331473 151.76120331 154.24909189 156.73698047 159.22486904
 161.71275762 164.2006462  166.68853478 169.17642336 171.66431194
 174.15220052 176.6400891  179.12797768 181.61586625 184.10375483
 186.59164341

In [237]:
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

print(x_int)
print(y_int)

[ 0.00000000e+00 -3.73131229e-01 -2.59817608e+00 -3.26212050e+00
 -2.18442687e+00 -2.98929946e-02  2.42923642e+00  4.54913599e+00
  5.92318348e+00  6.35117933e+00  5.82369277e+00  4.46259540e+00
  2.47320794e+00  1.09577220e-01 -2.36575300e+00 -4.71261671e+00
 -6.72701769e+00 -8.25541575e+00 -9.18486120e+00 -9.46381505e+00
 -9.11085788e+00 -8.12875279e+00 -6.63306046e+00 -4.69271059e+00
 -2.44736165e+00 -2.05444585e-02  2.46101146e+00  4.86841760e+00
  7.08937968e+00  9.02539126e+00  1.05948609e+01  1.17357250e+01
  1.24068974e+01  1.25885805e+01  1.22815267e+01  1.15053927e+01
  1.02963689e+01  8.70429550e+00  6.78948686e+00  4.61716636e+00
  2.25853448e+00 -1.98731680e-01 -2.68040566e+00 -5.11543300e+00
 -7.41973991e+00 -9.53891040e+00 -1.14237629e+01 -1.29919305e+01
 -1.42355069e+01 -1.51243232e+01 -1.56061571e+01 -1.57219415e+01
 -1.54217066e+01 -1.47579136e+01 -1.37255236e+01 -1.23634834e+01
 -1.07024632e+01 -8.78327367e+00 -6.65029558e+00 -4.35514246e+00
 -1.94290275e+00  5.28038

In [238]:
# 99. Given an integer n and a 2D array X, select from X the rows 
#     which can be interpreted as draws from a multinomial distribution with n degrees, 
#     i.e., the rows which only contain integers and which sum to n.

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [239]:
# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X 
#      (i.e., resample the elements of an array with replacement N times, 
#      compute the mean of each sample, and then compute percentiles over the means). 

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples

print(X)

[ 2.01660184  1.20549715 -0.73962574  0.73318267 -0.93083824 -0.35504042
  1.0518758   0.5970375  -2.06631994 -1.88601798  0.4704244  -1.39478631
  1.80135974  0.14404375 -1.69450496 -0.01042489 -0.10966598 -0.33974333
  0.78944559  2.38678234  0.37139793 -0.52191427 -1.27152467 -0.37406624
 -0.32279161 -0.76080043  0.86608739  0.15629382 -0.23799423 -0.79263557
  1.28466046 -0.80608898  0.50276195 -0.28474775 -1.3506007   0.39610695
 -0.04221677 -0.0861874  -1.82497759  0.55576578  0.11540374 -0.44073041
 -0.02176215  0.68156562 -0.34267914 -0.43184327  0.60784624 -0.54113472
 -0.65320078 -1.19476974 -3.30559669 -0.6066668   0.2102883   0.816365
 -0.61098207 -0.65634502  0.47399377 -0.3688341   1.81439628  0.17319743
 -0.07937653 -0.2952138   1.16953876 -0.86736715  0.24106342 -0.52136991
  1.83422726 -1.17692903  0.12040017 -1.02926712 -0.1554137  -0.55747448
 -0.91027019 -0.19243918 -0.19276855  0.03076135 -1.27562743 -0.30055273
  0.37607991 -1.6022685   1.30368995  1.31583192 -0.8

In [240]:

idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.28814908  0.08215439]


## To Be Continued...