# OOPs Concepts in python

# which is in four types
- Classes and Objects
- Encapsulation
- Abstraction
- Inheritance
- Polymorphism

``class classname:
    
    
    
    def method1
    .
    .
    
    def method2
    .
    .
    .
    .
    def methodn

In [38]:
# create simple class

class person:
    name = 'sam'
    age = 26
    def method1(cls):
        print('Your name is: ',cls.name)
    def method2(cls):
        print('Your age is: ',cls.age)

In [39]:
p.name

NameError: name 'p' is not defined

In [40]:
p.method1()

NameError: name 'p' is not defined

In [41]:
p.age

NameError: name 'p' is not defined

In [42]:
p.method2()

NameError: name 'p' is not defined

In [43]:
p = person()  # call class

## Encapsulation

`__init__(self)`

### It tells about the location / address

### Doc string (Multiple lines of commenting sectio for the documentation purpose) """   """


In [44]:
class employee:
    # DocString
    """
    employee(name = 'Sandeep',age= 'Age')
    """
    # Initialize the cariable
    def __init__(self,n,a):
        self.name = n
        self.age = a
        
    # Method
    def details(self):
        print('Hi {} you current is {}'.format(self.name,self.age))

In [45]:
e = employee('Sandeep',26) 

In [46]:
e.details()

Hi Sandeep you current is 26


In [47]:
# Salary details class

class salary:
    def __init__(self,name='.',age=0):
        self.name = name
        self.age = age
    def sal(self,amount):
        self.amount = amount
        print('Hi {} \n'.format(self.name))
        print('Your current salary is {}'.format(self.amount))

In [48]:
s = salary()

In [49]:
s.sal(50000)

Hi . 

Your current salary is 50000


In [50]:
# to Modify the sal

class salary:
    def __init__(self,name='.',age=0):
        self.name = name
        self.age = age
    def sal(self,amount):
        self.amount = amount
        print('Hi {} \n'.format(self.name))
        print('Your current salary is {}'.format(self.amount))
        
    #Modify the amount
    def modify(self,increment):
        self.amount += increment

In [51]:
s1 = salary()

In [52]:
name = input('Enter your Name: ')
age = int(input('Enter your age: '))
amount = float(input('Enter your salary:'))
s1 = salary(name,age)
s1.sal(amount)

if s1.amount > 30000:
    print('Congrats you got an Increment !!!')
    s1.modify(30000)
    print('Your current salary is {}'.format(amount))

Enter your Name: 666
Enter your age: 5
Enter your salary:666
Hi 666 

Your current salary is 666.0


In [53]:
s1.amount

666.0

In [54]:
# Abstraction to Perform the Banking Operation

class BankAccount(object):
    def __init__(self, initial_balance=0):
        self.balance = initial_balance
    def deposit(self, amount):
        self.balance += amount
    def withdraw(self, amount):
        self.balance -= amount


withdraw = float(input('Enter the amount to withdraw:'))

bal = 5000
my_account = BankAccount(bal)
my_account.withdraw(withdraw)

print("Hi Sandeep \nAcc No: xxxxx1234")

if my_account.balance < 0:
    print ('Transaction Failed')
    print ('Your Current Balance is',bal)
else:
    print ('Transaction Successful')
    print ('{} has been debited'.format(withdraw))
    print ('Your Current Balance is:',my_account.balance)



Enter the amount to withdraw:666
Hi Sandeep 
Acc No: xxxxx1234
Transaction Successful
666.0 has been debited
Your Current Balance is: 4334.0


In [55]:
import functools
functools.reduce(lambda x,y: x+y, [4,1,2,3])

10

## Inheritance

In [56]:
from PIL import Image
from numpy import*

temp=asarray(Image.open('image.jpg'))
print(temp)
print(temp.shape)

[[[105 119 207]
  [106 120 208]
  [105 120 205]
  ...
  [ 73  91 189]
  [ 72  92 187]
  [ 70  93 187]]

 [[106 121 206]
  [107 122 207]
  [106 121 206]
  ...
  [ 74  90 188]
  [ 71  90 185]
  [ 70  93 187]]

 [[106 121 204]
  [107 122 205]
  [107 122 205]
  ...
  [ 77  93 191]
  [ 73  92 187]
  [ 69  92 186]]

 ...

 [[ 13  12  20]
  [ 15  13  24]
  [ 17  15  26]
  ...
  [151  66  59]
  [153  65  61]
  [142  61  58]]

 [[ 15  13  24]
  [ 16  14  25]
  [ 14  12  23]
  ...
  [152  67  62]
  [154  66  62]
  [150  66  64]]

 [[ 21  17  31]
  [ 15  13  24]
  [ 12  10  21]
  ...
  [153  65  63]
  [156  66  65]
  [152  66  65]]]
(1920, 2160, 3)


In [57]:
from PIL import Image
from numpy import*

temp=asarray(Image.open('image.jpg'))
x=temp.shape[0]
y=temp.shape[1]*temp.shape[2]

temp.resize((x,y)) # a 2D array
print(temp)
print(temp.shape)

[[105 119 207 ...  70  93 187]
 [106 121 206 ...  70  93 187]
 [106 121 204 ...  69  92 186]
 ...
 [ 13  12  20 ... 142  61  58]
 [ 15  13  24 ... 150  66  64]
 [ 21  17  31 ... 152  66  65]]
(1920, 6480)


In [58]:
    from PIL import Image
    from numpy import*
     
    temp=Image.open('image.jpg')
    temp=temp.convert('1')      # Convert to black&white
    A = array(temp)             # Creates an array, white pixels==True and black pixels==False
    new_A=empty((A.shape[0],A.shape[1]),None)    #New array with same size as A

In [59]:
print(new_A.shape)

(1920, 2160)


In [61]:
class Polygon:
    def __init__(self, no_of_sides):
        self.n = no_of_sides
        self.sides = [0 for i in range(no_of_sides)]

    def inputSides(self):
        self.sides = [float(input("Enter side "+str(i+1)+" : ")) for i in range(self.n)]

    def dispSides(self):
        for i in range(self.n):
            print("Side",i+1,"is",self.sides[i])


p1 = Ploygon()
p1.inputSides()

NameError: name 'Ploygon' is not defined